repos:
-   repo: local
    hooks:
    -   id: yarn-build-production
        name: Build src files
        language: system
        entry: bash -c "yarn build:production"
        files: ^src/*
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.6
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8