name: continuous-integration

on: [push, pull_request]

jobs:

  lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Node/yarn
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pre-commit
        pip install -e .
        yarn install

    - name: Lint
      run: |
        pre-commit run --all-files


  # Build docs on a number of Python versions. In the future this can be
  # where tests go.
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r docs/requirements.txt

    # Build the docs
    - name: Build docs to store
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"
        sphinx-build -b html docs/ docs/_build/html -W --keep-going
